# Name of your site. Used to uniquely configure containers.
service: najlepsza_demokracja

# Name of the container image.
image: meceo/najlepsza_demokracja

# Deploy to these servers.
servers:
  - 37.27.38.0

# Use GIT_URL from env to auto-update site via git pulls.
# Remember to run `kamal env push` after making changes!
env:
  secret:
    - GIT_URL

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: meceo

  # Always use an access token rather than real password when possible.
  password:
    - SKIFF_REGISTRY_PASSWORD

# Check /up against 80
healthcheck:
  port: 80

# Use a different ssh user than root
# ssh:
#   user: app
